version: '3.9'

services:

  # php service
  php:
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile


  # db service - configure
  mysql:
    image: mysql:8
  # Add the MYSQL_ROOT_PASSWORD to the environment variables
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}

  # configure php - this node hast to remove
  #php:
  # build: game/docker/build/php <- Remove this node
  # build:
  # context: .
  # dockerfile: docker/build/php/Dockerfile
  # ports:
  # - '8100:80'


